package com.ccm.mzjhapp.ws.shmj.regn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-07-03T10:21:15.628+08:00
 * Generated source version: 3.1.16
 * 
 */
@WebService(targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", name = "IRegnAppointmentWsServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IRegnAppointmentWsServicePortTypeSH {

    @WebMethod
    @RequestWrapper(localName = "queryRegnAppintmentInfo", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.QueryRegnAppintmentInfo")
    @ResponseWrapper(localName = "queryRegnAppintmentInfoResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.QueryRegnAppintmentInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    String queryRegnAppintmentInfo(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );

    @WebMethod
    @RequestWrapper(localName = "queryRegnAppointmentInfo", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.QueryRegnAppointmentInfo")
    @ResponseWrapper(localName = "queryRegnAppointmentInfoResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.QueryRegnAppointmentInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    String queryRegnAppointmentInfo(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );

    @WebMethod
    @RequestWrapper(localName = "regnAppointmentToVisit", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.RegnAppointmentToVisit")
    @ResponseWrapper(localName = "regnAppointmentToVisitResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.RegnAppointmentToVisitResponse")
    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    String regnAppointmentToVisit(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );

    @WebMethod
    @RequestWrapper(localName = "queryRegnAppointmentTime", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.QueryRegnAppointmentTime")
    @ResponseWrapper(localName = "queryRegnAppointmentTimeResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.QueryRegnAppointmentTimeResponse")
    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    String queryRegnAppointmentTime(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );

    @WebMethod
    @RequestWrapper(localName = "queryRegnAppointmentRequest", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.QueryRegnAppointmentRequest")
    @ResponseWrapper(localName = "queryRegnAppointmentRequestResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.QueryRegnAppointmentRequestResponse")
    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    String queryRegnAppointmentRequest(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );

    @WebMethod
    @RequestWrapper(localName = "queryRegnAppointmentResource", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.QueryRegnAppointmentResource")
    @ResponseWrapper(localName = "queryRegnAppointmentResourceResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.QueryRegnAppointmentResourceResponse")
    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    String queryRegnAppointmentResource(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );

    @WebMethod
    @RequestWrapper(localName = "regnAppointmentRequest", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.RegnAppointmentRequest")
    @ResponseWrapper(localName = "regnAppointmentRequestResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.RegnAppointmentRequestResponse")
    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    String regnAppointmentRequest(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );

    @WebMethod
    @RequestWrapper(localName = "cancelRegnAppointment", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.CancelRegnAppointment")
    @ResponseWrapper(localName = "cancelRegnAppointmentResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.CancelRegnAppointmentResponse")
    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    String cancelRegnAppointment(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );

    @WebMethod
    @RequestWrapper(localName = "regnAppointment", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.RegnAppointment")
    @ResponseWrapper(localName = "regnAppointmentResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.regn.RegnAppointmentResponse")
    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    String regnAppointment(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );
}
