package com.ccm.mzjhapp.ws.shmj.regn;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-07-03T10:21:15.677+08:00
 * Generated source version: 3.1.16
 * 
 */
@WebServiceClient(name = "IRegnAppointmentWsService", 
                  wsdlLocation = "http://42.159.239.54:28080/eHealth/services/IRegnAppointmentWsService?wsdl",
                  targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com") 
public class IRegnAppointmentWsServiceSH extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", "IRegnAppointmentWsService");
    public final static QName IRegnAppointmentWsServiceHttpPort = new QName("http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", "IRegnAppointmentWsServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://42.159.239.54:28080/eHealth/services/IRegnAppointmentWsService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IRegnAppointmentWsServiceSH.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://42.159.239.54:28080/eHealth/services/IRegnAppointmentWsService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IRegnAppointmentWsServiceSH(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IRegnAppointmentWsServiceSH(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IRegnAppointmentWsServiceSH() {
        super(WSDL_LOCATION, SERVICE);
    }



    /**
     *
     * @return
     *     returns IRegnAppointmentWsServicePortType
     */
    @WebEndpoint(name = "IRegnAppointmentWsServiceHttpPort")
    public IRegnAppointmentWsServicePortTypeSH getIRegnAppointmentWsServiceHttpPort() {
        return super.getPort(IRegnAppointmentWsServiceHttpPort, IRegnAppointmentWsServicePortTypeSH.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRegnAppointmentWsServicePortType
     */
    @WebEndpoint(name = "IRegnAppointmentWsServiceHttpPort")
    public IRegnAppointmentWsServicePortTypeSH getIRegnAppointmentWsServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(IRegnAppointmentWsServiceHttpPort, IRegnAppointmentWsServicePortTypeSH.class, features);
    }

}
