package com.ccm.mzjhapp.ws.shmj.lisris;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2018-07-02T10:24:56.815+08:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://webservice.datong.webservice.server.ehealth.kompakar.com", name = "ILisRisReportWsServicePortTypeSH")
@XmlSeeAlso({ObjectFactory.class})
public interface ILisRisReportWsServicePortTypeSH {

    @WebResult(name = "out", targetNamespace = "http://webservice.datong.webservice.server.ehealth.kompakar.com")
    @RequestWrapper(localName = "MJCloud_GetReportInfo", targetNamespace = "http://webservice.datong.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.lisris.MJCloudGetReportInfo")
    @WebMethod(operationName = "MJCloud_GetReportInfo")
    @ResponseWrapper(localName = "MJCloud_GetReportInfoResponse", targetNamespace = "http://webservice.datong.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.lisris.MJCloudGetReportInfoResponse")
    String mjCloudGetReportInfo(
            @WebParam(name = "in0", targetNamespace = "http://webservice.datong.webservice.server.ehealth.kompakar.com")
                    String in0
    );

    @WebResult(name = "out", targetNamespace = "http://webservice.datong.webservice.server.ehealth.kompakar.com")
    @RequestWrapper(localName = "MJCloud_GetCostInfo", targetNamespace = "http://webservice.datong.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.lisris.MJCloudGetCostInfo")
    @WebMethod(operationName = "MJCloud_GetCostInfo")
    @ResponseWrapper(localName = "MJCloud_GetCostInfoResponse", targetNamespace = "http://webservice.datong.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.lisris.MJCloudGetCostInfoResponse")
    String mjCloudGetCostInfo(
            @WebParam(name = "in0", targetNamespace = "http://webservice.datong.webservice.server.ehealth.kompakar.com")
                    String in0
    );
}
