package com.ccm.mzjhapp.ws.shmj.pmi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2018-07-02T10:25:15.443+08:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", name = "IPmiWsServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IPmiWsServicePortTypeSH {

    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    @RequestWrapper(localName = "updatePatientInfo", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.pmi.UpdatePatientInfo")
    @WebMethod
    @ResponseWrapper(localName = "updatePatientInfoResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.pmi.UpdatePatientInfoResponse")
    String updatePatientInfo(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );

    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    @RequestWrapper(localName = "queryPatientInfo", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.pmi.QueryPatientInfo")
    @WebMethod
    @ResponseWrapper(localName = "queryPatientInfoResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.pmi.QueryPatientInfoResponse")
    String queryPatientInfo(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );

    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    @RequestWrapper(localName = "createPatient", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.pmi.CreatePatient")
    @WebMethod
    @ResponseWrapper(localName = "createPatientResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.pmi.CreatePatientResponse")
    String createPatient(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );

    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    @RequestWrapper(localName = "queryDoctor", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.pmi.QueryDoctor")
    @WebMethod
    @ResponseWrapper(localName = "queryDoctorResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.pmi.QueryDoctorResponse")
    String queryDoctor(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );

    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    @RequestWrapper(localName = "queryDept", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.pmi.QueryDept")
    @WebMethod
    @ResponseWrapper(localName = "queryDeptResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.pmi.QueryDeptResponse")
    String queryDept(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );

    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    @RequestWrapper(localName = "signPatient", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.pmi.SignPatient")
    @WebMethod
    @ResponseWrapper(localName = "signPatientResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.pmi.SignPatientResponse")
    String signPatient(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );

    @WebResult(name = "out", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
    @RequestWrapper(localName = "cancelSignPatient", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.pmi.CancelSignPatient")
    @WebMethod
    @ResponseWrapper(localName = "cancelSignPatientResponse", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com", className = "com.ccm.ws.shmj.pmi.CancelSignPatientResponse")
    String cancelSignPatient(
            @WebParam(name = "in0", targetNamespace = "http://wsservice.integratedservices.webservice.server.ehealth.kompakar.com")
                    String in0
    );
}
